<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HP" failures="0" tests="5" name="mypackage.TestNGTimeout" time="1.628" errors="1" timestamp="2020-03-08T16:04:36 IST" skipped="0">
  <testcase classname="mypackage.TestNGTimeout" name="testcase2" time="0.004"/>
  <testcase classname="mypackage.TestNGTimeout" name="testcase3" time="0.004"/>
  <testcase classname="mypackage.TestNGTimeout" name="testcase1" time="0.211">
    <error message="Method mypackage.TestNGTimeout.testcase1() didn&#039;t finish within the time-out 100" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method mypackage.TestNGTimeout.testcase1() didn't finish within the time-out 100
at java.base@13.0.2/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1031)
at java.base@13.0.2/java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1541)
at java.base@13.0.2/java.lang.invoke.MethodType$ConcurrentWeakInternSet.add(MethodType.java:1380)
at java.base@13.0.2/java.lang.invoke.MethodType.makeImpl(MethodType.java:327)
at java.base@13.0.2/java.lang.invoke.MethodHandleNatives.findMethodHandleType(MethodHandleNatives.java:377)
at java.base@13.0.2/java.util.concurrent.FutureTask.setException(FutureTask.java:249)
at java.base@13.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:269)
at java.base@13.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@13.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@13.0.2/java.lang.Thread.run(Thread.java:830)
]]>
    </error>
  </testcase> <!-- testcase1 -->
  <testcase classname="mypackage.TestNGTimeout" name="timeTestTwo" time="0.404"/>
  <testcase classname="mypackage.TestNGTimeout" name="timeTestOne" time="1.005"/>
</testsuite> <!-- mypackage.TestNGTimeout -->
